### ISSUE TITLE
collecting problem on one character

### ISSUE THREAD

**Issue by stresskiller** [madcowfred/wowthing_collector#6]
for some strange reason  i get a lua error on one specific character my tauren paladin : 

Message: Interface\AddOns\WoWthing_Collector\Collector.lua:867: attempt to compare nil with number
Time: 04/20/17 10:23:45
Count: 1
Stack: [C]: ?
Interface\AddOns\WoWthing_Collector\Collector.lua:867: in function `ParseArtifactLink'
Interface\AddOns\WoWthing_Collector\Collector.lua:825: in function `ScanBag'
Interface\AddOns\WoWthing_Collector\Collector.lua:519: in function `Timer'
Interface\AddOns\WoWthing_Collector\Collector.lua:579: in function <Interface\AddOns\WoWthing_Collector\Collector.lua:579>
Interface\SharedXML\C_TimerAugment.lua:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

**Comment by TymberAJ** [comment]
I had this same issue on my hunter with Titanstrike, although it's now in line 874 with the latest update. The issue is that either `itemParts[bonusCountIndex])` or `itemParts[bonusCountIndex+1]` is nil for some weapons, presumably tier 2 weapons given the section of code.

I was able to fix it for my hunter by adding the nil checks:
`    if tonumber(itemParts[bonusCountIndex]) == nil or tonumber(itemParts[bonusCountIndex+1]) == nil then 
        artifact.tier = 2
    else
        if tonumber(itemParts[bonusCountIndex]) == 1 and tonumber(itemParts[bonusCountIndex+1]) <= 3 then
            bonusCountIndex = bonusCountIndex + 1
            artifact.tier = 2
        end
    end
`

The itemString for the offending Titanstrike is:  `item:128861::146932:147076:133763::::110:253:16777472:9:1:726:448:1::3:3564:1467:3528:3:1727:1522:3336`

Ping me if there's anything I can do to help diagnose the issue better.
